# Header
menu:
  首页: /
  标签: /tags
  分类: /categories
  归档: /archives
  关于: /about
  RSS: /atom.xml

# Content
excerpt_link: 阅读更多

# Sidebar
author:
  name: Yakeing
  work: Web Developer &amp; Program design
  location: Guangzhou, Guangdong, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: /svg/github.svg
    url: https://github.com/yakeing
  - svg: /svg/weibo.svg
    url: https://weibo.com/yakeing
  - svg: /svg/twitter.svg
    url: https://twitter.com/yakeing

# 百度统计
baidu:
  id: 7655bbc8fe60302eb3ff0108b4652744

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
